In [2]:
import pandas as pd
import folium
import matplotlib.pyplot as plt

%matplotlib inline

from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

In [3]:
df = pd.read_csv("SemiFinalDF.csv")
df

,Unnamed: 0,City,Latitude,Longitude,Population,Population_Density,Total Talukas,UrbanPopPercentage,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,SchoolsWithPlaygrounds,SchoolsWithComputers,Venue Counts
0,0,AHMEDABAD,23.021624,72.579707,7045313,983.0,10,28.30,22.31,903.0,86.65,2912,28401,2671,2582,100
1,1,AMRELI,22.373810,73.044198,1513614,224.0,11,41.01,8.59,964.0,74.49,1041,8032,911,959,4
2,2,ANAND,22.563200,72.960280,2090276,446.0,8,22.76,12.57,921.0,85.79,1382,10633,1083,1029,19
3,3,PALANPUR,21.208740,72.776320,3116045,245.0,14,20.93,24.43,936.0,66.39,2730,19361,2031,1854,92
4,4,BHARUCH,21.701400,72.962690,1550822,238.0,9,79.68,13.14,924.0,83.03,1221,8949,851,1008,7
5,5,BHAVNAGAR,23.026430,72.644310,2393272,287.0,10,30.32,16.53,931.0,76.84,1329,12448,1021,1238,50
6,6,AHWA,20.759700,73.690100,226769,129.0,3,30.74,21.44,1007.0,76.80,425,2138,292,196,1
7,7,GANDHINAGAR,23.223288,72.649227,1387478,641.0,4,84.05,12.15,920.0,85.78,1002,9413,819,888,24
8,8,JAMNAGAR,22.470140,70.057710,1407635,167.0,6,48.77,13.38,938.0,74.40,1059,7441,736,833,14
9,9,JUNAGADH,21.517411,70.464276,1525605,300.0,10,25.49,12.01,952.0,76.88,1243,9003,987,1049,5
10,10,BHUJ,23.247245,69.668339,2090313,46.0,10,13.27,32.03,907.0,71.58,2121,13397,1564,1565,13
11,11,NADIAD,22.698010,72.856750,2053769,560.0,10,14.00,12.81,937.0,84.31,1633,10557,1385,1043,5
12,12,MEHSANA,23.582720,72.145890,2027727,419.0,11,14.96,9.91,925.0,84.26,1291,10893,1174,1156,4
13,13,RAJPIPLA,21.870640,73.504290,590379,215.0,5,34.07,14.77,960.0,73.29,791,3491,416,383,3
14,14,NAVSARI,20.952407,72.932383,1330711,602.0,6,37.23,8.24,961.0,84.78,905,6254,570,704,9
15,15,GODHRA,22.831730,74.243920,1642268,502.0,7,8.99,17.92,945.0,72.32,1599,9598,1009,1034,7
16,16,PATAN,23.853500,72.147830,1342746,234.0,9,25.35,13.53,935.0,73.47,965,7523,731,774,5
17,17,PORBANDAR,21.639150,69.612160,586062,255.0,3,33.05,9.17,947.0,76.63,458,3378,360,327,8
18,18,RAJKOT,22.304587,70.802098,3015229,399.0,11,44.96,19.87,924.0,82.20,1990,16583,1738,1842,42
19,19,HIMMATNAGAR,23.351750,72.959690,1388671,333.0,8,43.21,16.56,950.0,76.60,1534,9622,1255,1109,3
20,20,SURAT,21.100530,72.866540,6079231,1337.0,10,10.89,42.19,788.0,86.65,2447,25624,2054,1935,8
21,21,SURENDRANAGAR,22.735220,71.637910,1585268,171.0,10,58.12,15.89,929.0,73.19,1143,8947,839,1007,6
22,22,VYARA,21.112100,73.396100,806489,248.0,7,46.06,12.07,1004.0,69.23,922,4387,638,460,4
23,23,VADODARA,22.322280,73.176440,3093795,718.0,8,10.44,14.16,934.0,81.21,1724,15259,1329,1062,100
24,24,VALSAD,20.587900,72.935260,1703068,561.0,6,9.79,20.74,926.0,80.94,1284,9392,788,786,8

In [4]:
df.columns

Index(['Unnamed: 0', 'City', 'Latitude', 'Longitude', 'Population',
       'Population_Density', 'Total Talukas', 'UrbanPopPercentage',
       'GrowthRate', 'SexRatio', 'LiteracyRate', 'Total Schools', 'Teachers',
       'SchoolsWithPlaygrounds', 'SchoolsWithComputers', 'Venue Counts'],
      dtype='object')

In [5]:
df = df[['City', 'Latitude', 'Longitude', 'Population','GrowthRate', 'SexRatio', 'LiteracyRate', 'Total Schools', 'Teachers', 'Venue Counts']]
df

,City,Latitude,Longitude,Population,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,Venue Counts
0,AHMEDABAD,23.021624,72.579707,7045313,22.31,903.0,86.65,2912,28401,100
1,AMRELI,22.373810,73.044198,1513614,8.59,964.0,74.49,1041,8032,4
2,ANAND,22.563200,72.960280,2090276,12.57,921.0,85.79,1382,10633,19
3,PALANPUR,21.208740,72.776320,3116045,24.43,936.0,66.39,2730,19361,92
4,BHARUCH,21.701400,72.962690,1550822,13.14,924.0,83.03,1221,8949,7
5,BHAVNAGAR,23.026430,72.644310,2393272,16.53,931.0,76.84,1329,12448,50
6,AHWA,20.759700,73.690100,226769,21.44,1007.0,76.80,425,2138,1
7,GANDHINAGAR,23.223288,72.649227,1387478,12.15,920.0,85.78,1002,9413,24
8,JAMNAGAR,22.470140,70.057710,1407635,13.38,938.0,74.40,1059,7441,14
9,JUNAGADH,21.517411,70.464276,1525605,12.01,952.0,76.88,1243,9003,5
10,BHUJ,23.247245,69.668339,2090313,32.03,907.0,71.58,2121,13397,13
11,NADIAD,22.698010,72.856750,2053769,12.81,937.0,84.31,1633,10557,5
12,MEHSANA,23.582720,72.145890,2027727,9.91,925.0,84.26,1291,10893,4
13,RAJPIPLA,21.870640,73.504290,590379,14.77,960.0,73.29,791,3491,3
14,NAVSARI,20.952407,72.932383,1330711,8.24,961.0,84.78,905,6254,9
15,GODHRA,22.831730,74.243920,1642268,17.92,945.0,72.32,1599,9598,7
16,PATAN,23.853500,72.147830,1342746,13.53,935.0,73.47,965,7523,5
17,PORBANDAR,21.639150,69.612160,586062,9.17,947.0,76.63,458,3378,8
18,RAJKOT,22.304587,70.802098,3015229,19.87,924.0,82.20,1990,16583,42
19,HIMMATNAGAR,23.351750,72.959690,1388671,16.56,950.0,76.60,1534,9622,3
20,SURAT,21.100530,72.866540,6079231,42.19,788.0,86.65,2447,25624,8
21,SURENDRANAGAR,22.735220,71.637910,1585268,15.89,929.0,73.19,1143,8947,6
22,VYARA,21.112100,73.396100,806489,12.07,1004.0,69.23,922,4387,4
23,VADODARA,22.322280,73.176440,3093795,14.16,934.0,81.21,1724,15259,100
24,VALSAD,20.587900,72.935260,1703068,20.74,926.0,80.94,1284,9392,8

In [11]:
df.sort_values('Population', ascending=False,inplace=True)
df

/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,City,Latitude,Longitude,Population,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,Venue Counts
0,AHMEDABAD,23.021624,72.579707,7045313,22.31,903.0,86.65,2912,28401,100
20,SURAT,21.100530,72.866540,6079231,42.19,788.0,86.65,2447,25624,8
3,PALANPUR,21.208740,72.776320,3116045,24.43,936.0,66.39,2730,19361,92
23,VADODARA,22.322280,73.176440,3093795,14.16,934.0,81.21,1724,15259,100
18,RAJKOT,22.304587,70.802098,3015229,19.87,924.0,82.20,1990,16583,42
5,BHAVNAGAR,23.026430,72.644310,2393272,16.53,931.0,76.84,1329,12448,50
10,BHUJ,23.247245,69.668339,2090313,32.03,907.0,71.58,2121,13397,13
2,ANAND,22.563200,72.960280,2090276,12.57,921.0,85.79,1382,10633,19
11,NADIAD,22.698010,72.856750,2053769,12.81,937.0,84.31,1633,10557,5
12,MEHSANA,23.582720,72.145890,2027727,9.91,925.0,84.26,1291,10893,4
24,VALSAD,20.587900,72.935260,1703068,20.74,926.0,80.94,1284,9392,8
15,GODHRA,22.831730,74.243920,1642268,17.92,945.0,72.32,1599,9598,7
21,SURENDRANAGAR,22.735220,71.637910,1585268,15.89,929.0,73.19,1143,8947,6
4,BHARUCH,21.701400,72.962690,1550822,13.14,924.0,83.03,1221,8949,7
9,JUNAGADH,21.517411,70.464276,1525605,12.01,952.0,76.88,1243,9003,5
1,AMRELI,22.373810,73.044198,1513614,8.59,964.0,74.49,1041,8032,4
8,JAMNAGAR,22.470140,70.057710,1407635,13.38,938.0,74.40,1059,7441,14
19,HIMMATNAGAR,23.351750,72.959690,1388671,16.56,950.0,76.60,1534,9622,3
7,GANDHINAGAR,23.223288,72.649227,1387478,12.15,920.0,85.78,1002,9413,24
16,PATAN,23.853500,72.147830,1342746,13.53,935.0,73.47,965,7523,5
14,NAVSARI,20.952407,72.932383,1330711,8.24,961.0,84.78,905,6254,9
22,VYARA,21.112100,73.396100,806489,12.07,1004.0,69.23,922,4387,4
13,RAJPIPLA,21.870640,73.504290,590379,14.77,960.0,73.29,791,3491,3
17,PORBANDAR,21.639150,69.612160,586062,9.17,947.0,76.63,458,3378,8
6,AHWA,20.759700,73.690100,226769,21.44,1007.0,76.80,425,2138,1

In [12]:
df.reset_index(inplace=True)
df

,index,City,Latitude,Longitude,Population,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,Venue Counts
0,0,AHMEDABAD,23.021624,72.579707,7045313,22.31,903.0,86.65,2912,28401,100
1,20,SURAT,21.100530,72.866540,6079231,42.19,788.0,86.65,2447,25624,8
2,3,PALANPUR,21.208740,72.776320,3116045,24.43,936.0,66.39,2730,19361,92
3,23,VADODARA,22.322280,73.176440,3093795,14.16,934.0,81.21,1724,15259,100
4,18,RAJKOT,22.304587,70.802098,3015229,19.87,924.0,82.20,1990,16583,42
5,5,BHAVNAGAR,23.026430,72.644310,2393272,16.53,931.0,76.84,1329,12448,50
6,10,BHUJ,23.247245,69.668339,2090313,32.03,907.0,71.58,2121,13397,13
7,2,ANAND,22.563200,72.960280,2090276,12.57,921.0,85.79,1382,10633,19
8,11,NADIAD,22.698010,72.856750,2053769,12.81,937.0,84.31,1633,10557,5
9,12,MEHSANA,23.582720,72.145890,2027727,9.91,925.0,84.26,1291,10893,4
10,24,VALSAD,20.587900,72.935260,1703068,20.74,926.0,80.94,1284,9392,8
11,15,GODHRA,22.831730,74.243920,1642268,17.92,945.0,72.32,1599,9598,7
12,21,SURENDRANAGAR,22.735220,71.637910,1585268,15.89,929.0,73.19,1143,8947,6
13,4,BHARUCH,21.701400,72.962690,1550822,13.14,924.0,83.03,1221,8949,7
14,9,JUNAGADH,21.517411,70.464276,1525605,12.01,952.0,76.88,1243,9003,5
15,1,AMRELI,22.373810,73.044198,1513614,8.59,964.0,74.49,1041,8032,4
16,8,JAMNAGAR,22.470140,70.057710,1407635,13.38,938.0,74.40,1059,7441,14
17,19,HIMMATNAGAR,23.351750,72.959690,1388671,16.56,950.0,76.60,1534,9622,3
18,7,GANDHINAGAR,23.223288,72.649227,1387478,12.15,920.0,85.78,1002,9413,24
19,16,PATAN,23.853500,72.147830,1342746,13.53,935.0,73.47,965,7523,5
20,14,NAVSARI,20.952407,72.932383,1330711,8.24,961.0,84.78,905,6254,9
21,22,VYARA,21.112100,73.396100,806489,12.07,1004.0,69.23,922,4387,4
22,13,RAJPIPLA,21.870640,73.504290,590379,14.77,960.0,73.29,791,3491,3
23,17,PORBANDAR,21.639150,69.612160,586062,9.17,947.0,76.63,458,3378,8
24,6,AHWA,20.759700,73.690100,226769,21.44,1007.0,76.80,425,2138,1

In [13]:
df.drop('index',axis=1,inplace=True)
df

/home/jupyterlab/conda/lib/python3.6/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

,City,Latitude,Longitude,Population,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,Venue Counts
0,AHMEDABAD,23.021624,72.579707,7045313,22.31,903.0,86.65,2912,28401,100
1,SURAT,21.100530,72.866540,6079231,42.19,788.0,86.65,2447,25624,8
2,PALANPUR,21.208740,72.776320,3116045,24.43,936.0,66.39,2730,19361,92
3,VADODARA,22.322280,73.176440,3093795,14.16,934.0,81.21,1724,15259,100
4,RAJKOT,22.304587,70.802098,3015229,19.87,924.0,82.20,1990,16583,42
5,BHAVNAGAR,23.026430,72.644310,2393272,16.53,931.0,76.84,1329,12448,50
6,BHUJ,23.247245,69.668339,2090313,32.03,907.0,71.58,2121,13397,13
7,ANAND,22.563200,72.960280,2090276,12.57,921.0,85.79,1382,10633,19
8,NADIAD,22.698010,72.856750,2053769,12.81,937.0,84.31,1633,10557,5
9,MEHSANA,23.582720,72.145890,2027727,9.91,925.0,84.26,1291,10893,4
10,VALSAD,20.587900,72.935260,1703068,20.74,926.0,80.94,1284,9392,8
11,GODHRA,22.831730,74.243920,1642268,17.92,945.0,72.32,1599,9598,7
12,SURENDRANAGAR,22.735220,71.637910,1585268,15.89,929.0,73.19,1143,8947,6
13,BHARUCH,21.701400,72.962690,1550822,13.14,924.0,83.03,1221,8949,7
14,JUNAGADH,21.517411,70.464276,1525605,12.01,952.0,76.88,1243,9003,5
15,AMRELI,22.373810,73.044198,1513614,8.59,964.0,74.49,1041,8032,4
16,JAMNAGAR,22.470140,70.057710,1407635,13.38,938.0,74.40,1059,7441,14
17,HIMMATNAGAR,23.351750,72.959690,1388671,16.56,950.0,76.60,1534,9622,3
18,GANDHINAGAR,23.223288,72.649227,1387478,12.15,920.0,85.78,1002,9413,24
19,PATAN,23.853500,72.147830,1342746,13.53,935.0,73.47,965,7523,5
20,NAVSARI,20.952407,72.932383,1330711,8.24,961.0,84.78,905,6254,9
21,VYARA,21.112100,73.396100,806489,12.07,1004.0,69.23,922,4387,4
22,RAJPIPLA,21.870640,73.504290,590379,14.77,960.0,73.29,791,3491,3
23,PORBANDAR,21.639150,69.612160,586062,9.17,947.0,76.63,458,3378,8
24,AHWA,20.759700,73.690100,226769,21.44,1007.0,76.80,425,2138,1

In [20]:
df = df[0:20]
df

,City,Latitude,Longitude,Population,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,Venue Counts
0,AHMEDABAD,23.021624,72.579707,7045313,22.31,903.0,86.65,2912,28401,100
1,SURAT,21.100530,72.866540,6079231,42.19,788.0,86.65,2447,25624,8
2,PALANPUR,21.208740,72.776320,3116045,24.43,936.0,66.39,2730,19361,92
3,VADODARA,22.322280,73.176440,3093795,14.16,934.0,81.21,1724,15259,100
4,RAJKOT,22.304587,70.802098,3015229,19.87,924.0,82.20,1990,16583,42
5,BHAVNAGAR,23.026430,72.644310,2393272,16.53,931.0,76.84,1329,12448,50
6,BHUJ,23.247245,69.668339,2090313,32.03,907.0,71.58,2121,13397,13
7,ANAND,22.563200,72.960280,2090276,12.57,921.0,85.79,1382,10633,19
8,NADIAD,22.698010,72.856750,2053769,12.81,937.0,84.31,1633,10557,5
9,MEHSANA,23.582720,72.145890,2027727,9.91,925.0,84.26,1291,10893,4
10,VALSAD,20.587900,72.935260,1703068,20.74,926.0,80.94,1284,9392,8
11,GODHRA,22.831730,74.243920,1642268,17.92,945.0,72.32,1599,9598,7
12,SURENDRANAGAR,22.735220,71.637910,1585268,15.89,929.0,73.19,1143,8947,6
13,BHARUCH,21.701400,72.962690,1550822,13.14,924.0,83.03,1221,8949,7
14,JUNAGADH,21.517411,70.464276,1525605,12.01,952.0,76.88,1243,9003,5
15,AMRELI,22.373810,73.044198,1513614,8.59,964.0,74.49,1041,8032,4
16,JAMNAGAR,22.470140,70.057710,1407635,13.38,938.0,74.40,1059,7441,14
17,HIMMATNAGAR,23.351750,72.959690,1388671,16.56,950.0,76.60,1534,9622,3
18,GANDHINAGAR,23.223288,72.649227,1387478,12.15,920.0,85.78,1002,9413,24
19,PATAN,23.853500,72.147830,1342746,13.53,935.0,73.47,965,7523,5

In [21]:
df.to_csv("ReallyFinalDF.csv")

In [36]:
df.loc[1,'Venue Counts'] = 100
df

/home/jupyterlab/conda/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,City,Latitude,Longitude,Population,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,Venue Counts
0,AHMEDABAD,23.021624,72.579707,7045313,22.31,903.0,86.65,2912,28401,100
1,SURAT,21.100530,72.866540,6079231,42.19,788.0,86.65,2447,25624,100
2,PALANPUR,21.208740,72.776320,3116045,24.43,936.0,66.39,2730,19361,92
3,VADODARA,22.322280,73.176440,3093795,14.16,934.0,81.21,1724,15259,100
4,RAJKOT,22.304587,70.802098,3015229,19.87,924.0,82.20,1990,16583,42
5,BHAVNAGAR,23.026430,72.644310,2393272,16.53,931.0,76.84,1329,12448,50
6,BHUJ,23.247245,69.668339,2090313,32.03,907.0,71.58,2121,13397,13
7,ANAND,22.563200,72.960280,2090276,12.57,921.0,85.79,1382,10633,19
8,NADIAD,22.698010,72.856750,2053769,12.81,937.0,84.31,1633,10557,5
9,MEHSANA,23.582720,72.145890,2027727,9.91,925.0,84.26,1291,10893,4
10,VALSAD,20.587900,72.935260,1703068,20.74,926.0,80.94,1284,9392,8
11,GODHRA,22.831730,74.243920,1642268,17.92,945.0,72.32,1599,9598,7
12,SURENDRANAGAR,22.735220,71.637910,1585268,15.89,929.0,73.19,1143,8947,6
13,BHARUCH,21.701400,72.962690,1550822,13.14,924.0,83.03,1221,8949,7
14,JUNAGADH,21.517411,70.464276,1525605,12.01,952.0,76.88,1243,9003,5
15,AMRELI,22.373810,73.044198,1513614,8.59,964.0,74.49,1041,8032,4
16,JAMNAGAR,22.470140,70.057710,1407635,13.38,938.0,74.40,1059,7441,14
17,HIMMATNAGAR,23.351750,72.959690,1388671,16.56,950.0,76.60,1534,9622,3
18,GANDHINAGAR,23.223288,72.649227,1387478,12.15,920.0,85.78,1002,9413,24
19,PATAN,23.853500,72.147830,1342746,13.53,935.0,73.47,965,7523,5

In [37]:
df.to_csv("ReallyFinalDF.csv")

In [38]:
X = df.values[:,3:].astype(float)
X_scaled = MinMaxScaler().fit_transform(X)
X_scaled

array([[1.        , 0.40833333, 0.65340909, 1.        , 1.        ,
        1.        , 1.        ],
       [0.83058822, 1.        , 0.        , 1.        , 0.76117103,
        0.86750954, 1.        ],
       [0.31096504, 0.47142857, 0.84090909, 0.        , 0.90652286,
        0.56870229, 0.91752577],
       [0.30706329, 0.16577381, 0.82954545, 0.73149062, 0.38983051,
        0.37299618, 1.        ],
       [0.29328599, 0.33571429, 0.77272727, 0.78035538, 0.52645095,
        0.43616412, 0.40206186],
       [0.18421984, 0.23630952, 0.8125    , 0.51579467, 0.18695429,
        0.23888359, 0.48453608],
       [0.13109307, 0.69761905, 0.67613636, 0.25616979, 0.59373395,
        0.28416031, 0.10309278],
       [0.13108658, 0.11845238, 0.75568182, 0.95755183, 0.21417565,
        0.15229008, 0.16494845],
       [0.12468473, 0.12559524, 0.84659091, 0.88450148, 0.34309194,
        0.14866412, 0.02061856],
       [0.12011801, 0.03928571, 0.77840909, 0.88203356, 0.16743708,
        0.16469466, 0.01030928],
       [0.06318593, 0.36160714, 0.78409091, 0.71816387, 0.16384181,
        0.09308206, 0.05154639],
       [0.05252407, 0.27767857, 0.89204545, 0.29269497, 0.32562917,
        0.10291031, 0.04123711],
       [0.04252857, 0.2172619 , 0.80113636, 0.33563672, 0.0914227 ,
        0.07185115, 0.03092784],
       [0.03648813, 0.13541667, 0.77272727, 0.8213228 , 0.13148433,
        0.07194656, 0.04123711],
       [0.03206609, 0.10178571, 0.93181818, 0.517769  , 0.14278377,
        0.0745229 , 0.02061856],
       [0.02996335, 0.        , 1.        , 0.39980257, 0.03903441,
        0.02819656, 0.01030928],
       [0.01137891, 0.14255952, 0.85227273, 0.39536032, 0.0482794 ,
        0.        , 0.11340206],
       [0.00805339, 0.23720238, 0.92045455, 0.50394867, 0.29224448,
        0.10405534, 0.        ],
       [0.00784419, 0.10595238, 0.75      , 0.95705824, 0.0190036 ,
        0.09408397, 0.21649485],
       [0.        , 0.14702381, 0.83522727, 0.34945706, 0.        ,
        0.00391221, 0.02061856]])

In [45]:
num_clusters = 4

k_means = KMeans(init="k-means++", n_clusters=num_clusters, n_init=20)
k_means.fit(X_scaled)
labels = k_means.labels_

print(labels)

[1 1 3 3 3 3 3 2 2 2 2 0 0 2 0 0 0 0 2 0]

In [46]:
df['ClusterLabels'] = labels
df

/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,City,Latitude,Longitude,Population,GrowthRate,SexRatio,LiteracyRate,Total Schools,Teachers,Venue Counts,ClusterLabels
0,AHMEDABAD,23.021624,72.579707,7045313,22.31,903.0,86.65,2912,28401,100,1
1,SURAT,21.100530,72.866540,6079231,42.19,788.0,86.65,2447,25624,100,1
2,PALANPUR,21.208740,72.776320,3116045,24.43,936.0,66.39,2730,19361,92,3
3,VADODARA,22.322280,73.176440,3093795,14.16,934.0,81.21,1724,15259,100,3
4,RAJKOT,22.304587,70.802098,3015229,19.87,924.0,82.20,1990,16583,42,3
5,BHAVNAGAR,23.026430,72.644310,2393272,16.53,931.0,76.84,1329,12448,50,3
6,BHUJ,23.247245,69.668339,2090313,32.03,907.0,71.58,2121,13397,13,3
7,ANAND,22.563200,72.960280,2090276,12.57,921.0,85.79,1382,10633,19,2
8,NADIAD,22.698010,72.856750,2053769,12.81,937.0,84.31,1633,10557,5,2
9,MEHSANA,23.582720,72.145890,2027727,9.91,925.0,84.26,1291,10893,4,2
10,VALSAD,20.587900,72.935260,1703068,20.74,926.0,80.94,1284,9392,8,2
11,GODHRA,22.831730,74.243920,1642268,17.92,945.0,72.32,1599,9598,7,0
12,SURENDRANAGAR,22.735220,71.637910,1585268,15.89,929.0,73.19,1143,8947,6,0
13,BHARUCH,21.701400,72.962690,1550822,13.14,924.0,83.03,1221,8949,7,2
14,JUNAGADH,21.517411,70.464276,1525605,12.01,952.0,76.88,1243,9003,5,0
15,AMRELI,22.373810,73.044198,1513614,8.59,964.0,74.49,1041,8032,4,0
16,JAMNAGAR,22.470140,70.057710,1407635,13.38,938.0,74.40,1059,7441,14,0
17,HIMMATNAGAR,23.351750,72.959690,1388671,16.56,950.0,76.60,1534,9622,3,0
18,GANDHINAGAR,23.223288,72.649227,1387478,12.15,920.0,85.78,1002,9413,24,2
19,PATAN,23.853500,72.147830,1342746,13.53,935.0,73.47,965,7523,5,0

In [47]:
df.to_csv("ReallyFinalDFwithClustering.csv")